# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: grammY

permissions:
    contents: read

on:
    push:
        branches: [main, v2]
    pull_request:
        branches: [main, v2]

jobs:
    backport:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install --ignore-scripts

            - name: Run backporting
              run: npm run backport

    format-and-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Check Format
              run: deno fmt --check

            - name: Lint
              run: deno lint

    test:
        runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

        strategy:
            matrix:
                os: [macOS-latest, windows-latest, ubuntu-latest]

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Cache Dependencies
              run: deno task check

            - name: Run Tests
              run: deno task test

    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Create coverage files
              run: deno task coverage

            - name: Collect coverage
              uses: codecov/codecov-action@v5
              with:
                  files: ./coverage.lcov
/**
 * @title Inline Keyboards
 * @deno run --allow-net bot.ts
 * @deno_cli <url>
 * @resource {https://grammy.dev/plugins/keyboard.html#inline-keyboards} Docs: Inline Keyboards
 *
 * Attach buttons to messages.
 */

// Inline keyboards are sets of buttons that are displayed underneath messages.
// grammY has a simple and intuitive way to build up the inline keyboards that your bot can send along with a message.

// Lets setup the bot as we seen in the Hello World example.
import { Bot, InlineKeyboard } from "https://deno.land/x/grammy@v1.11.0/mod.ts";
const bot = new Bot("8684473988:AAFlpuZjPYdjLLG5lEpGgnRSLJ-Fz1C9-_Q");

// Construct a keyboard.
const inlineKeyboard = new InlineKeyboard().text("click", "click-payload");

// You can also add link buttons.
inlineKeyboard.url("grammY docs", "https://grammy.dev");

// Send a keyboard along with a message.
bot.command("start", async (ctx) => {
  await ctx.reply("Curious? Click me!", { reply_markup: inlineKeyboard });
});

// Wait for click events with specific callback data.
bot.callbackQuery("click-payload", async (ctx) => {
  await ctx.answerCallbackQuery("You were curious, indeed!");
});
